title       = "ostep"
baseURL     = "https://ostep-cli.tamnd.com/"
description = "A command line for ostep."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ostep-cli"
